import type { FeatureFlag } from '../models/system.model';

/** Flag keys referenced from routes, menus and templates. */
export const FEATURE_FLAGS = {
  liveDraw: 'draws.live',
  autoDraw: 'draws.auto',
  posDevices: 'retailers.pos-devices',
  qrValidation: 'tickets.qr-validation',
  walletTransfer: 'wallet.transfer',
  paymentReconciliation: 'payment.reconciliation',
  campaigns: 'notifications.campaigns',
  advancedReports: 'reports.advanced',
  commandPalette: 'ui.command-palette',
  dashboardCustomisation: 'ui.dashboard-customisation',
  whiteLabelling: 'settings.white-labelling',
  multiTenant: 'settings.multi-tenant',
  offlineMode: 'system.offline-mode',
  realtimeNotifications: 'system.realtime-notifications',
} as const;

/** Seeded flag state. Replace the loader with a `/feature-flags` call later. */
export const DEFAULT_FEATURE_FLAGS: FeatureFlag[] = [
  {
    key: FEATURE_FLAGS.liveDraw,
    name: 'Live Draw Studio',
    description: 'Streamed draw console with real-time number entry and witness sign-off.',
    enabled: true,
    module: 'Draws',
    roles: [],
    rolloutPercent: 100,
    updatedAt: '2026-05-02T08:15:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.autoDraw,
    name: 'Automatic Draw Engine',
    description: 'RNG-driven draws executed by the scheduler without an operator.',
    enabled: true,
    module: 'Draws',
    roles: [],
    rolloutPercent: 100,
    updatedAt: '2026-04-18T04:40:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.posDevices,
    name: 'POS Device Management',
    description: 'Register, activate and monitor retailer point-of-sale terminals.',
    enabled: true,
    module: 'Retailers',
    roles: [],
    rolloutPercent: 100,
    updatedAt: '2026-03-30T11:05:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.qrValidation,
    name: 'QR / Barcode Validation',
    description: 'Scan-based ticket validation at the counter.',
    enabled: true,
    module: 'Tickets',
    roles: [],
    rolloutPercent: 100,
    updatedAt: '2026-06-01T02:00:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.walletTransfer,
    name: 'Wallet-to-Wallet Transfer',
    description: 'Internal balance movement between agents, retailers and customers.',
    enabled: true,
    module: 'Wallet',
    roles: [],
    rolloutPercent: 100,
    updatedAt: '2026-05-22T09:30:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.paymentReconciliation,
    name: 'Gateway Reconciliation',
    description: 'Daily statement matching against gateway settlement files.',
    enabled: true,
    module: 'Payments',
    roles: [],
    rolloutPercent: 100,
    updatedAt: '2026-06-11T06:45:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.campaigns,
    name: 'Marketing Campaigns',
    description: 'Segmented multi-channel campaign scheduling.',
    enabled: true,
    module: 'Notifications',
    roles: [],
    rolloutPercent: 100,
    updatedAt: '2026-02-14T13:20:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.advancedReports,
    name: 'Advanced Analytics',
    description: 'Cohort, profitability and exposure analytics.',
    enabled: true,
    module: 'Reports',
    roles: [],
    rolloutPercent: 100,
    updatedAt: '2026-06-20T15:00:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.commandPalette,
    name: 'Command Palette',
    description: 'Ctrl/⌘+K quick navigation and actions.',
    enabled: true,
    module: 'Interface',
    roles: [],
    rolloutPercent: 100,
    updatedAt: '2026-01-09T07:10:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.dashboardCustomisation,
    name: 'Dashboard Customisation',
    description: 'Drag, resize, pin and hide dashboard widgets.',
    enabled: true,
    module: 'Interface',
    roles: [],
    rolloutPercent: 100,
    updatedAt: '2026-05-05T10:25:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.whiteLabelling,
    name: 'White Labelling',
    description: 'Per-operator branding, templates and regional formats.',
    enabled: true,
    module: 'Settings',
    roles: ['SUPER_ADMIN', 'ADMIN'],
    rolloutPercent: 100,
    updatedAt: '2026-04-02T05:55:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.multiTenant,
    name: 'Multi-Tenant Operations',
    description: 'Operate several lottery operators from one deployment.',
    enabled: false,
    module: 'Settings',
    roles: ['SUPER_ADMIN'],
    rolloutPercent: 0,
    updatedAt: '2026-06-28T12:00:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.offlineMode,
    name: 'Offline-Friendly Mode',
    description: 'Service-worker backed read-only access when connectivity drops.',
    enabled: true,
    module: 'Platform',
    roles: [],
    rolloutPercent: 100,
    updatedAt: '2026-03-15T08:00:00.000Z',
    updatedBy: 'System',
  },
  {
    key: FEATURE_FLAGS.realtimeNotifications,
    name: 'Realtime Notifications',
    description: 'WebSocket push into the notification centre.',
    enabled: true,
    module: 'Platform',
    roles: [],
    rolloutPercent: 100,
    updatedAt: '2026-07-01T03:35:00.000Z',
    updatedBy: 'System',
  },
];
