import type { NavItem } from '../models/navigation.model';
import { FEATURE_FLAGS } from './feature-flags.constants';
import { PERMISSIONS } from './permission.constants';

/**
 * Master navigation tree.
 *
 * The sidebar, command palette and breadcrumb fallbacks all derive from this
 * single source. Entries are filtered at render time by RBAC and feature flags,
 * so adding a module here is the only step needed to expose it.
 */
export const NAVIGATION: NavItem[] = [
  {
    id: 'section-overview',
    labelKey: 'nav.section.overview',
    label: 'Overview',
    sectionTitle: true,
  },
  {
    id: 'dashboard',
    labelKey: 'nav.dashboard',
    label: 'Dashboard',
    icon: 'space_dashboard',
    route: '/dashboard',
    permissions: [PERMISSIONS.dashboard.view],
    keywords: ['home', 'overview', 'kpi', 'summary'],
  },
  {
    id: 'section-operations',
    labelKey: 'nav.section.operations',
    label: 'Operations',
    sectionTitle: true,
  },
  {
    id: 'lottery',
    labelKey: 'nav.lottery',
    label: 'Lottery',
    icon: 'casino',
    permissions: [PERMISSIONS.lottery.view],
    keywords: ['game', 'product', 'digit', 'animal'],
    children: [
      {
        id: 'lottery-games',
        labelKey: 'nav.lottery.games',
        label: 'Lottery Types',
        icon: 'grid_view',
        route: '/lottery',
        permissions: [PERMISSIONS.lottery.view],
      },
      {
        id: 'lottery-configuration',
        labelKey: 'nav.lottery.configuration',
        label: 'Configuration',
        icon: 'tune',
        route: '/lottery/configuration',
        permissions: [PERMISSIONS.lottery.configure],
      },
      {
        id: 'lottery-prizes',
        labelKey: 'nav.lottery.prizes',
        label: 'Prize Structure',
        icon: 'emoji_events',
        route: '/lottery/prizes',
        permissions: [PERMISSIONS.lottery.prizes],
      },
    ],
  },
  {
    id: 'draws',
    labelKey: 'nav.draws',
    label: 'Draw Management',
    icon: 'stadia_controller',
    permissions: [PERMISSIONS.draws.view],
    badge: { key: 'pendingDraws', tone: 'warning' },
    keywords: ['draw', 'result', 'publish', 'rollback'],
    children: [
      {
        id: 'draws-list',
        labelKey: 'nav.draws.all',
        label: 'All Draws',
        icon: 'list_alt',
        route: '/draws',
        permissions: [PERMISSIONS.draws.view],
      },
      {
        id: 'draws-schedule',
        labelKey: 'nav.draws.schedule',
        label: 'Schedule',
        icon: 'event',
        route: '/draws/schedule',
        permissions: [PERMISSIONS.draws.schedule],
      },
      {
        id: 'draws-live',
        labelKey: 'nav.draws.live',
        label: 'Live Draw Studio',
        icon: 'sensors',
        route: '/draws/live',
        permissions: [PERMISSIONS.draws.execute],
        featureFlag: FEATURE_FLAGS.liveDraw,
        badge: { key: 'liveDraw', tone: 'danger' },
      },
      {
        id: 'draws-results',
        labelKey: 'nav.draws.results',
        label: 'Results & Verification',
        icon: 'fact_check',
        route: '/draws/results',
        permissions: [PERMISSIONS.draws.verify],
      },
    ],
  },
  {
    id: 'tickets',
    labelKey: 'nav.tickets',
    label: 'Tickets',
    icon: 'confirmation_number',
    permissions: [PERMISSIONS.tickets.view],
    keywords: ['ticket', 'bet', 'stake', 'winner', 'claim'],
    children: [
      {
        id: 'tickets-list',
        labelKey: 'nav.tickets.all',
        label: 'All Tickets',
        icon: 'receipt_long',
        route: '/tickets',
        permissions: [PERMISSIONS.tickets.view],
      },
      {
        id: 'tickets-winning',
        labelKey: 'nav.tickets.winning',
        label: 'Winning Tickets',
        icon: 'workspace_premium',
        route: '/tickets/winning',
        permissions: [PERMISSIONS.tickets.view],
      },
      {
        id: 'tickets-cancelled',
        labelKey: 'nav.tickets.cancelled',
        label: 'Cancelled Tickets',
        icon: 'cancel',
        route: '/tickets/cancelled',
        permissions: [PERMISSIONS.tickets.view],
      },
      {
        id: 'tickets-validate',
        labelKey: 'nav.tickets.validate',
        label: 'Validate Ticket',
        icon: 'qr_code_scanner',
        route: '/tickets/validate',
        permissions: [PERMISSIONS.tickets.validate],
        featureFlag: FEATURE_FLAGS.qrValidation,
      },
    ],
  },
  {
    id: 'section-network',
    labelKey: 'nav.section.network',
    label: 'Distribution Network',
    sectionTitle: true,
  },
  {
    id: 'agents',
    labelKey: 'nav.agents',
    label: 'Agents',
    icon: 'handshake',
    permissions: [PERMISSIONS.agents.view],
    keywords: ['agent', 'master', 'distributor', 'commission'],
    children: [
      {
        id: 'agents-list',
        labelKey: 'nav.agents.all',
        label: 'All Agents',
        icon: 'groups',
        route: '/agents',
        permissions: [PERMISSIONS.agents.view],
      },
      {
        id: 'agents-approvals',
        labelKey: 'nav.agents.approvals',
        label: 'KYC & Approvals',
        icon: 'assignment_turned_in',
        route: '/agents/approvals',
        permissions: [PERMISSIONS.agents.approve],
        badge: { key: 'pendingAgentApprovals', tone: 'warning' },
      },
      {
        id: 'agents-commission',
        labelKey: 'nav.agents.commission',
        label: 'Commission Plans',
        icon: 'percent',
        route: '/agents/commission',
        permissions: [PERMISSIONS.agents.commission],
      },
      {
        id: 'agents-performance',
        labelKey: 'nav.agents.performance',
        label: 'Performance',
        icon: 'trending_up',
        route: '/agents/performance',
        permissions: [PERMISSIONS.agents.view],
      },
    ],
  },
  {
    id: 'retailers',
    labelKey: 'nav.retailers',
    label: 'Retailers',
    icon: 'storefront',
    permissions: [PERMISSIONS.retailers.view],
    keywords: ['shop', 'pos', 'device', 'terminal', 'outlet'],
    children: [
      {
        id: 'retailers-list',
        labelKey: 'nav.retailers.shops',
        label: 'Retail Shops',
        icon: 'store',
        route: '/retailers',
        permissions: [PERMISSIONS.retailers.view],
      },
      {
        id: 'retailers-devices',
        labelKey: 'nav.retailers.devices',
        label: 'POS Devices',
        icon: 'point_of_sale',
        route: '/retailers/devices',
        permissions: [PERMISSIONS.retailers.devices],
        featureFlag: FEATURE_FLAGS.posDevices,
      },
      {
        id: 'retailers-map',
        labelKey: 'nav.retailers.map',
        label: 'Coverage Map',
        icon: 'map',
        route: '/retailers/map',
        permissions: [PERMISSIONS.retailers.view],
      },
    ],
  },
  {
    id: 'section-finance',
    labelKey: 'nav.section.finance',
    label: 'Finance',
    sectionTitle: true,
  },
  {
    id: 'wallet',
    labelKey: 'nav.wallet',
    label: 'Wallet',
    icon: 'account_balance_wallet',
    permissions: [PERMISSIONS.wallet.view],
    keywords: ['balance', 'deposit', 'withdraw', 'freeze'],
    children: [
      {
        id: 'wallet-accounts',
        labelKey: 'nav.wallet.accounts',
        label: 'Wallet Accounts',
        icon: 'wallet',
        route: '/wallet',
        permissions: [PERMISSIONS.wallet.view],
      },
      {
        id: 'wallet-transactions',
        labelKey: 'nav.wallet.transactions',
        label: 'Transactions',
        icon: 'swap_horiz',
        route: '/wallet/transactions',
        permissions: [PERMISSIONS.wallet.view],
      },
      {
        id: 'wallet-transfer',
        labelKey: 'nav.wallet.transfer',
        label: 'Transfer & Adjust',
        icon: 'sync_alt',
        route: '/wallet/transfer',
        permissions: [PERMISSIONS.wallet.transfer],
        featureFlag: FEATURE_FLAGS.walletTransfer,
      },
      {
        id: 'wallet-settlement',
        labelKey: 'nav.wallet.settlement',
        label: 'Settlements',
        icon: 'receipt',
        route: '/wallet/settlement',
        permissions: [PERMISSIONS.agents.settlement],
      },
    ],
  },
  {
    id: 'payment',
    labelKey: 'nav.payment',
    label: 'Payments',
    icon: 'payments',
    permissions: [PERMISSIONS.payment.view],
    badge: { key: 'failedPayments', tone: 'danger' },
    keywords: ['gateway', 'bank', 'refund', 'reconcile'],
    children: [
      {
        id: 'payment-transactions',
        labelKey: 'nav.payment.transactions',
        label: 'Transactions',
        icon: 'credit_score',
        route: '/payment',
        permissions: [PERMISSIONS.payment.view],
      },
      {
        id: 'payment-gateways',
        labelKey: 'nav.payment.gateways',
        label: 'Payment Gateways',
        icon: 'hub',
        route: '/payment/gateways',
        permissions: [PERMISSIONS.payment.gateways],
      },
      {
        id: 'payment-banks',
        labelKey: 'nav.payment.banks',
        label: 'Banks',
        icon: 'account_balance',
        route: '/payment/banks',
        permissions: [PERMISSIONS.payment.banks],
      },
      {
        id: 'payment-refunds',
        labelKey: 'nav.payment.refunds',
        label: 'Refunds',
        icon: 'undo',
        route: '/payment/refunds',
        permissions: [PERMISSIONS.payment.refund],
      },
      {
        id: 'payment-reconciliation',
        labelKey: 'nav.payment.reconciliation',
        label: 'Reconciliation',
        icon: 'rule',
        route: '/payment/reconciliation',
        permissions: [PERMISSIONS.payment.reconcile],
        featureFlag: FEATURE_FLAGS.paymentReconciliation,
      },
    ],
  },
  {
    id: 'section-administration',
    labelKey: 'nav.section.administration',
    label: 'Administration',
    sectionTitle: true,
  },
  {
    id: 'users',
    labelKey: 'nav.users',
    label: 'User Management',
    icon: 'group',
    permissions: [PERMISSIONS.users.view],
    keywords: ['user', 'staff', 'customer', 'role', 'permission'],
    children: [
      {
        id: 'users-list',
        labelKey: 'nav.users.all',
        label: 'All Users',
        icon: 'people',
        route: '/users',
        permissions: [PERMISSIONS.users.view],
      },
      {
        id: 'users-roles',
        labelKey: 'nav.users.roles',
        label: 'Roles',
        icon: 'badge',
        route: '/users/roles',
        permissions: [PERMISSIONS.roles.view],
      },
      {
        id: 'users-permissions',
        labelKey: 'nav.users.permissions',
        label: 'Permission Matrix',
        icon: 'lock_person',
        route: '/users/permissions',
        permissions: [PERMISSIONS.roles.assignPermissions],
      },
      {
        id: 'users-verification',
        labelKey: 'nav.users.verification',
        label: 'Verification Queue',
        icon: 'verified_user',
        route: '/users/verification',
        permissions: [PERMISSIONS.users.approve],
        badge: { key: 'pendingKyc', tone: 'warning' },
      },
    ],
  },
  {
    id: 'notifications',
    labelKey: 'nav.notifications',
    label: 'Notifications',
    icon: 'notifications_active',
    permissions: [PERMISSIONS.notifications.view],
    keywords: ['push', 'sms', 'email', 'campaign', 'broadcast'],
    children: [
      {
        id: 'notifications-centre',
        labelKey: 'nav.notifications.centre',
        label: 'Notification Centre',
        icon: 'inbox',
        route: '/notifications',
        permissions: [PERMISSIONS.notifications.view],
        badge: { key: 'unreadNotifications', tone: 'primary' },
      },
      {
        id: 'notifications-templates',
        labelKey: 'nav.notifications.templates',
        label: 'Templates',
        icon: 'description',
        route: '/notifications/templates',
        permissions: [PERMISSIONS.notifications.templates],
      },
      {
        id: 'notifications-campaigns',
        labelKey: 'nav.notifications.campaigns',
        label: 'Campaigns',
        icon: 'campaign',
        route: '/notifications/campaigns',
        permissions: [PERMISSIONS.notifications.create],
        featureFlag: FEATURE_FLAGS.campaigns,
      },
      {
        id: 'notifications-segments',
        labelKey: 'nav.notifications.segments',
        label: 'Segments',
        icon: 'pie_chart',
        route: '/notifications/segments',
        permissions: [PERMISSIONS.notifications.segments],
      },
    ],
  },
  {
    id: 'reports',
    labelKey: 'nav.reports',
    label: 'Reports',
    icon: 'assessment',
    permissions: [PERMISSIONS.reports.view],
    keywords: ['sales', 'revenue', 'profit', 'tax', 'export'],
    children: [
      {
        id: 'reports-overview',
        labelKey: 'nav.reports.overview',
        label: 'Report Centre',
        icon: 'insights',
        route: '/reports',
        permissions: [PERMISSIONS.reports.view],
      },
      {
        id: 'reports-sales',
        labelKey: 'nav.reports.sales',
        label: 'Sales',
        icon: 'point_of_sale',
        route: '/reports/sales',
        permissions: [PERMISSIONS.reports.sales],
      },
      {
        id: 'reports-revenue',
        labelKey: 'nav.reports.revenue',
        label: 'Revenue & Profit',
        icon: 'savings',
        route: '/reports/revenue',
        permissions: [PERMISSIONS.reports.revenue],
      },
      {
        id: 'reports-commission',
        labelKey: 'nav.reports.commission',
        label: 'Commission',
        icon: 'percent',
        route: '/reports/commission',
        permissions: [PERMISSIONS.reports.commission],
      },
      {
        id: 'reports-tax',
        labelKey: 'nav.reports.tax',
        label: 'Tax',
        icon: 'request_quote',
        route: '/reports/tax',
        permissions: [PERMISSIONS.reports.tax],
      },
      {
        id: 'reports-winners',
        labelKey: 'nav.reports.winners',
        label: 'Winners',
        icon: 'military_tech',
        route: '/reports/winners',
        permissions: [PERMISSIONS.reports.winners],
      },
    ],
  },
  {
    id: 'audit',
    labelKey: 'nav.audit',
    label: 'Audit & Logs',
    icon: 'gavel',
    permissions: [PERMISSIONS.audit.view],
    keywords: ['log', 'security', 'trail', 'api', 'error'],
    children: [
      {
        id: 'audit-activity',
        labelKey: 'nav.audit.activity',
        label: 'Activity Audit',
        icon: 'history',
        route: '/audit',
        permissions: [PERMISSIONS.audit.view],
      },
      {
        id: 'audit-login',
        labelKey: 'nav.audit.login',
        label: 'Login Audit',
        icon: 'login',
        route: '/audit/login',
        permissions: [PERMISSIONS.audit.view],
      },
      {
        id: 'audit-transaction',
        labelKey: 'nav.audit.transaction',
        label: 'Transaction Audit',
        icon: 'receipt_long',
        route: '/audit/transaction',
        permissions: [PERMISSIONS.audit.view],
      },
      {
        id: 'audit-security',
        labelKey: 'nav.audit.security',
        label: 'Security Logs',
        icon: 'shield',
        route: '/audit/security',
        permissions: [PERMISSIONS.audit.security],
      },
      {
        id: 'audit-api',
        labelKey: 'nav.audit.api',
        label: 'API & Error Logs',
        icon: 'bug_report',
        route: '/audit/api',
        permissions: [PERMISSIONS.audit.api],
      },
    ],
  },
  {
    id: 'settings',
    labelKey: 'nav.settings',
    label: 'Settings',
    icon: 'settings',
    permissions: [PERMISSIONS.settings.view],
    keywords: ['configuration', 'theme', 'branding', 'appearance'],
    children: [
      {
        id: 'settings-general',
        labelKey: 'nav.settings.general',
        label: 'General',
        icon: 'tune',
        route: '/settings',
        permissions: [PERMISSIONS.settings.general],
      },
      {
        id: 'settings-appearance',
        labelKey: 'nav.settings.appearance',
        label: 'Appearance',
        icon: 'palette',
        route: '/settings/appearance',
        permissions: [PERMISSIONS.settings.appearance],
      },
      {
        id: 'settings-branding',
        labelKey: 'nav.settings.branding',
        label: 'Branding & White Label',
        icon: 'branding_watermark',
        route: '/settings/branding',
        permissions: [PERMISSIONS.settings.branding],
        featureFlag: FEATURE_FLAGS.whiteLabelling,
      },
      {
        id: 'settings-financial',
        labelKey: 'nav.settings.financial',
        label: 'Financial Rules',
        icon: 'account_balance',
        route: '/settings/financial',
        permissions: [PERMISSIONS.settings.commission],
      },
      {
        id: 'settings-notifications',
        labelKey: 'nav.settings.notifications',
        label: 'Notification Rules',
        icon: 'edit_notifications',
        route: '/settings/notifications',
        permissions: [PERMISSIONS.settings.notification],
      },
      {
        id: 'settings-feature-flags',
        labelKey: 'nav.settings.featureFlags',
        label: 'Feature Flags',
        icon: 'toggle_on',
        route: '/settings/feature-flags',
        permissions: [PERMISSIONS.settings.featureFlags],
      },
      {
        id: 'settings-about',
        labelKey: 'nav.settings.about',
        label: 'About & System',
        icon: 'info',
        route: '/settings/about',
        permissions: [PERMISSIONS.settings.view],
      },
    ],
  },
  {
    id: 'profile',
    labelKey: 'nav.profile',
    label: 'My Profile',
    icon: 'account_circle',
    route: '/profile',
    permissions: [PERMISSIONS.profile.view],
    keywords: ['me', 'account', 'password', 'security'],
  },
];

/** Flattens the tree to every entry that owns a route. */
export function flattenNavigation(items: readonly NavItem[] = NAVIGATION): NavItem[] {
  const output: NavItem[] = [];
  const walk = (nodes: readonly NavItem[]): void => {
    for (const node of nodes) {
      if (node.route) {
        output.push(node);
      }
      if (node.children?.length) {
        walk(node.children);
      }
    }
  };
  walk(items);
  return output;
}
