import type {
  BrandingSettings,
  RegionalSettings,
  ThemePalette,
  ThemePreset,
  ThemePresetId,
  ThemeSettings,
} from '../models/theme.model';

/** Neutral scaffolding shared by every light palette. */
const LIGHT_NEUTRALS = {
  background: '#f2f5fa',
  surface: '#f8fafc',
  surfaceElevated: '#ffffff',
  surfaceHover: '#eef2f9',
  border: '#dfe6f0',
  textPrimary: '#0f172a',
  textSecondary: '#475569',
  textMuted: '#8fa0b8',
} as const;

/** Neutral scaffolding shared by every dark palette. */
const DARK_NEUTRALS = {
  background: '#0a1120',
  surface: '#0f1a2e',
  surfaceElevated: '#15233c',
  surfaceHover: '#1c2c49',
  border: '#23334f',
  textPrimary: '#e9effb',
  textSecondary: '#a7b7d3',
  textMuted: '#6d7f9d',
} as const;

const LIGHT_STATUS = {
  success: '#12864d',
  warning: '#b45309',
  danger: '#c02626',
  info: '#0369a1',
} as const;

const DARK_STATUS = {
  success: '#34d399',
  warning: '#fbbf24',
  danger: '#f87171',
  info: '#60a5fa',
} as const;

interface PresetSeed {
  primary: string;
  secondary: string;
  accent: string;
  primaryContrast?: string;
  secondaryContrast?: string;
  accentContrast?: string;
  sidebar: string;
  sidebarText: string;
  sidebarActive: string;
  header: string;
  headerText: string;
  tableHeader: string;
}

function buildPalette(
  seed: PresetSeed,
  neutrals: typeof LIGHT_NEUTRALS | typeof DARK_NEUTRALS,
  status: typeof LIGHT_STATUS | typeof DARK_STATUS,
): ThemePalette {
  return {
    primary: seed.primary,
    primaryContrast: seed.primaryContrast ?? '#ffffff',
    secondary: seed.secondary,
    secondaryContrast: seed.secondaryContrast ?? '#ffffff',
    accent: seed.accent,
    accentContrast: seed.accentContrast ?? '#ffffff',
    success: status.success,
    warning: status.warning,
    danger: status.danger,
    info: status.info,
    background: neutrals.background,
    surface: neutrals.surface,
    surfaceElevated: neutrals.surfaceElevated,
    surfaceHover: neutrals.surfaceHover,
    border: neutrals.border,
    textPrimary: neutrals.textPrimary,
    textSecondary: neutrals.textSecondary,
    textMuted: neutrals.textMuted,
    sidebar: seed.sidebar,
    sidebarText: seed.sidebarText,
    sidebarActive: seed.sidebarActive,
    header: seed.header,
    headerText: seed.headerText,
    tableHeader: seed.tableHeader,
  };
}

function preset(
  id: ThemePresetId,
  name: string,
  description: string,
  light: PresetSeed,
  dark: PresetSeed,
  extra: Partial<Pick<ThemePreset, 'forcesGlass' | 'preferredMode'>> = {},
): ThemePreset {
  return {
    id,
    name,
    description,
    swatches: [light.primary, light.secondary, light.accent, dark.sidebar],
    light: buildPalette(light, LIGHT_NEUTRALS, LIGHT_STATUS),
    dark: buildPalette(dark, DARK_NEUTRALS, DARK_STATUS),
    ...extra,
  };
}

/** The thirteen shipped presets. Each supports light, dark and auto modes. */
export const THEME_PRESETS: readonly ThemePreset[] = [
  preset(
    'corporate-blue',
    'Corporate Blue',
    'Professional blue banking interface — the default operator experience.',
    {
      primary: '#1a56db',
      secondary: '#0e7490',
      accent: '#7c3aed',
      sidebar: '#0f2a5c',
      sidebarText: '#c7d7f5',
      sidebarActive: '#2563eb',
      header: '#ffffff',
      headerText: '#0f172a',
      tableHeader: '#eef3fc',
    },
    {
      primary: '#4f8cf7',
      secondary: '#22a3c3',
      accent: '#a78bfa',
      sidebar: '#0c1830',
      sidebarText: '#a8bde3',
      sidebarActive: '#2f6fe0',
      header: '#0f1a2e',
      headerText: '#e9effb',
      tableHeader: '#152546',
    },
  ),
  preset(
    'emerald-green',
    'Emerald Green',
    'Fresh fintech palette with emerald accents.',
    {
      primary: '#047857',
      secondary: '#0f766e',
      accent: '#65a30d',
      sidebar: '#06301f',
      sidebarText: '#bfe6d4',
      sidebarActive: '#059669',
      header: '#ffffff',
      headerText: '#052e22',
      tableHeader: '#e9f6f0',
    },
    {
      primary: '#34d399',
      secondary: '#2dd4bf',
      accent: '#a3e635',
      sidebar: '#06231a',
      sidebarText: '#9fd8c0',
      sidebarActive: '#10b981',
      header: '#0d1c2a',
      headerText: '#e6f5ee',
      tableHeader: '#12332a',
    },
  ),
  preset(
    'royal-purple',
    'Royal Purple',
    'Luxury violet treatment for premium operator brands.',
    {
      primary: '#6d28d9',
      secondary: '#9333ea',
      accent: '#db2777',
      sidebar: '#2c1065',
      sidebarText: '#d9cdf5',
      sidebarActive: '#7c3aed',
      header: '#ffffff',
      headerText: '#2c1065',
      tableHeader: '#f2ecfd',
    },
    {
      primary: '#a78bfa',
      secondary: '#c084fc',
      accent: '#f472b6',
      sidebar: '#1c0d3a',
      sidebarText: '#cdbdf0',
      sidebarActive: '#8b5cf6',
      header: '#150d28',
      headerText: '#ede9fe',
      tableHeader: '#241546',
    },
  ),
  preset(
    'banking-navy',
    'Banking Navy',
    'Conservative navy scheme aligned with central-bank reporting standards.',
    {
      primary: '#0b3d91',
      secondary: '#1e4f9c',
      accent: '#0891b2',
      sidebar: '#071d45',
      sidebarText: '#b8caea',
      sidebarActive: '#1d4ed8',
      header: '#ffffff',
      headerText: '#071d45',
      tableHeader: '#eaf0fa',
    },
    {
      primary: '#5b8ff0',
      secondary: '#7aa5f5',
      accent: '#22d3ee',
      sidebar: '#050f24',
      sidebarText: '#9fb4d9',
      sidebarActive: '#2563eb',
      header: '#0a1526',
      headerText: '#e4ecfb',
      tableHeader: '#12213d',
    },
  ),
  preset(
    'crimson-red',
    'Crimson Red',
    'High-energy red scheme for promotional and special-draw environments.',
    {
      primary: '#b91c1c',
      secondary: '#be123c',
      accent: '#ea580c',
      sidebar: '#450a0a',
      sidebarText: '#f0c9c9',
      sidebarActive: '#dc2626',
      header: '#ffffff',
      headerText: '#450a0a',
      tableHeader: '#fdeceb',
    },
    {
      primary: '#f87171',
      secondary: '#fb7185',
      accent: '#fb923c',
      sidebar: '#2a0808',
      sidebarText: '#e9b8b8',
      sidebarActive: '#ef4444',
      header: '#1c0d0d',
      headerText: '#fbe6e6',
      tableHeader: '#361414',
    },
  ),
  preset(
    'sunset-orange',
    'Sunset Orange',
    'Warm amber palette with strong daylight legibility.',
    {
      primary: '#c2410c',
      secondary: '#ea580c',
      accent: '#ca8a04',
      sidebar: '#43190a',
      sidebarText: '#f2d3bd',
      sidebarActive: '#f97316',
      header: '#ffffff',
      headerText: '#43190a',
      tableHeader: '#fdf0e6',
    },
    {
      primary: '#fb923c',
      secondary: '#fdba74',
      accent: '#facc15',
      sidebar: '#2a1206',
      sidebarText: '#ebc4a5',
      sidebarActive: '#f97316',
      header: '#1d1109',
      headerText: '#fdece0',
      tableHeader: '#3a1e0d',
    },
  ),
  preset(
    'teal',
    'Teal',
    'Calm teal scheme tuned for long analyst sessions.',
    {
      primary: '#0f766e',
      secondary: '#0e7490',
      accent: '#0284c7',
      sidebar: '#062b2b',
      sidebarText: '#bfe3e0',
      sidebarActive: '#14b8a6',
      header: '#ffffff',
      headerText: '#062b2b',
      tableHeader: '#e7f5f4',
    },
    {
      primary: '#2dd4bf',
      secondary: '#22d3ee',
      accent: '#38bdf8',
      sidebar: '#052222',
      sidebarText: '#a4d7d2',
      sidebarActive: '#14b8a6',
      header: '#0a1c22',
      headerText: '#e2f6f4',
      tableHeader: '#123033',
    },
  ),
  preset(
    'indigo',
    'Indigo',
    'Modern indigo palette with a Material 3 feel.',
    {
      primary: '#4338ca',
      secondary: '#4f46e5',
      accent: '#0ea5e9',
      sidebar: '#1e1b4b',
      sidebarText: '#c9c6f2',
      sidebarActive: '#6366f1',
      header: '#ffffff',
      headerText: '#1e1b4b',
      tableHeader: '#eeeefc',
    },
    {
      primary: '#818cf8',
      secondary: '#a5b4fc',
      accent: '#38bdf8',
      sidebar: '#131235',
      sidebarText: '#b9b6ea',
      sidebarActive: '#6366f1',
      header: '#0f1030',
      headerText: '#e8e8fb',
      tableHeader: '#1d1c46',
    },
  ),
  preset(
    'gold',
    'Executive Gold',
    'Black-and-gold premium styling for executive dashboards.',
    {
      primary: '#a16207',
      secondary: '#854d0e',
      accent: '#1f2937',
      sidebar: '#1c1917',
      sidebarText: '#e5d5ac',
      sidebarActive: '#ca8a04',
      header: '#ffffff',
      headerText: '#1c1917',
      tableHeader: '#faf3e2',
    },
    {
      primary: '#eab308',
      secondary: '#d4a017',
      accent: '#f5f5f4',
      accentContrast: '#1c1917',
      sidebar: '#0c0a09',
      sidebarText: '#dcc78d',
      sidebarActive: '#ca8a04',
      header: '#14110e',
      headerText: '#f7ecd2',
      tableHeader: '#241d13',
    },
    { preferredMode: 'dark' },
  ),
  preset(
    'dark-professional',
    'Dark Professional',
    'Balanced dark-first dashboard for control-room use.',
    {
      primary: '#334155',
      secondary: '#0f766e',
      accent: '#2563eb',
      sidebar: '#1e293b',
      sidebarText: '#cbd5e1',
      sidebarActive: '#3b82f6',
      header: '#ffffff',
      headerText: '#0f172a',
      tableHeader: '#eef2f7',
    },
    {
      primary: '#7dd3fc',
      primaryContrast: '#04283d',
      secondary: '#5eead4',
      secondaryContrast: '#04302b',
      accent: '#93c5fd',
      accentContrast: '#0b2545',
      sidebar: '#0b1220',
      sidebarText: '#b6c4dc',
      sidebarActive: '#38bdf8',
      header: '#0d1626',
      headerText: '#e2eaf7',
      tableHeader: '#152136',
    },
    { preferredMode: 'dark' },
  ),
  preset(
    'midnight-black',
    'Midnight Black',
    'Maximum-contrast black surface, ideal for OLED wall displays.',
    {
      primary: '#111827',
      secondary: '#374151',
      accent: '#6366f1',
      sidebar: '#000000',
      sidebarText: '#d1d5db',
      sidebarActive: '#4f46e5',
      header: '#ffffff',
      headerText: '#000000',
      tableHeader: '#f1f2f4',
    },
    {
      primary: '#e5e7eb',
      primaryContrast: '#0a0a0a',
      secondary: '#9ca3af',
      secondaryContrast: '#0a0a0a',
      accent: '#818cf8',
      sidebar: '#000000',
      sidebarText: '#b9bec7',
      sidebarActive: '#4f46e5',
      header: '#050505',
      headerText: '#f3f4f6',
      tableHeader: '#111111',
    },
    { preferredMode: 'dark' },
  ),
  preset(
    'glassmorphism',
    'Glassmorphism',
    'Translucent frosted surfaces layered over a gradient backdrop.',
    {
      primary: '#2563eb',
      secondary: '#7c3aed',
      accent: '#06b6d4',
      sidebar: '#1e3a8a',
      sidebarText: '#dbeafe',
      sidebarActive: '#3b82f6',
      header: '#ffffff',
      headerText: '#1e3a8a',
      tableHeader: '#edf3ff',
    },
    {
      primary: '#60a5fa',
      secondary: '#a78bfa',
      accent: '#22d3ee',
      sidebar: '#0b1530',
      sidebarText: '#c3d5f7',
      sidebarActive: '#3b82f6',
      header: '#0d1730',
      headerText: '#e3ecff',
      tableHeader: '#16234a',
    },
    { forcesGlass: true },
  ),
  preset(
    'minimal-white',
    'Minimal White',
    'Clean, low-chrome interface that keeps focus on the data.',
    {
      primary: '#111827',
      secondary: '#4b5563',
      accent: '#2563eb',
      sidebar: '#ffffff',
      sidebarText: '#374151',
      sidebarActive: '#111827',
      header: '#ffffff',
      headerText: '#111827',
      tableHeader: '#fafafa',
    },
    {
      primary: '#f3f4f6',
      primaryContrast: '#111827',
      secondary: '#d1d5db',
      secondaryContrast: '#111827',
      accent: '#93c5fd',
      accentContrast: '#0b2545',
      sidebar: '#0f1a2e',
      sidebarText: '#c2ccdb',
      sidebarActive: '#e5e7eb',
      header: '#0f1a2e',
      headerText: '#eef2f7',
      tableHeader: '#16233b',
    },
    { preferredMode: 'light' },
  ),
];

export const THEME_PRESET_MAP: ReadonlyMap<ThemePresetId, ThemePreset> = new Map(
  THEME_PRESETS.map((item) => [item.id, item]),
);

export const DEFAULT_THEME_SETTINGS: ThemeSettings = {
  presetId: 'banking-navy',
  mode: 'light',
  direction: 'ltr',
  overrides: {},
  typography: {
    fontFamily: 'inter',
    fontSize: 14,
    lineHeight: 1.55,
    letterSpacing: 0,
  },
  layout: {
    sidebar: 'expanded',
    header: 'fixed',
    contentWidth: 'fluid',
    navigation: 'left',
    sidebarPinned: true,
    showBreadcrumb: true,
    showFooter: true,
    showQuickPanel: true,
  },
  accessibility: {
    highContrast: false,
    colourBlindSafe: false,
    focusIndicators: true,
    largeTargets: false,
    screenReaderHints: true,
  },
  density: 'comfortable',
  borderRadius: 12,
  shadowIntensity: 2,
  buttonStyle: 'rounded',
  cardStyle: 'elevated',
  tableStyle: ['zebra', 'hover-highlight'],
  iconStyle: 'material-symbols',
  animationLevel: 'full',
  animationSpeed: 'normal',
  glassEffect: false,
  loginTheme: 'split',
};

export const FONT_STACKS: Record<string, string> = {
  inter: "'Inter', 'Noto Sans Lao', system-ui, -apple-system, 'Segoe UI', sans-serif",
  roboto: "'Roboto', 'Noto Sans Lao', system-ui, -apple-system, 'Segoe UI', sans-serif",
  poppins: "'Poppins', 'Noto Sans Lao', system-ui, -apple-system, 'Segoe UI', sans-serif",
  'open-sans': "'Open Sans', 'Noto Sans Lao', system-ui, -apple-system, 'Segoe UI', sans-serif",
  nunito: "'Nunito', 'Noto Sans Lao', system-ui, -apple-system, 'Segoe UI', sans-serif",
  'ibm-plex-sans': "'IBM Plex Sans', 'Noto Sans Lao', system-ui, -apple-system, 'Segoe UI', sans-serif",
};

export const DEFAULT_BRANDING: BrandingSettings = {
  applicationName: 'Lao National Lottery',
  applicationShortName: 'LL Admin',
  companyName: 'Lao National Lottery Enterprise',
  logoUrl: 'assets/images/logo.svg',
  logoDarkUrl: 'assets/images/logo-dark.svg',
  loginLogoUrl: 'assets/images/logo.svg',
  faviconUrl: 'assets/icons/favicon.svg',
  dashboardBannerUrl: 'https://picsum.photos/seed/lao-lottery-banner/1600/400',
  loginBackgroundUrl: 'https://picsum.photos/seed/vientiane-skyline/1920/1080',
  loginVideoUrl: '',
  loadingAnimationUrl: 'assets/images/loader.svg',
  loginWelcomeTitle: 'Welcome back',
  loginWelcomeMessage: 'Sign in to the National Lottery Management System.',
  footerText: 'Lao National Lottery Management System',
  copyright: `© ${new Date().getFullYear()} Lao National Lottery Enterprise. All rights reserved.`,
  supportEmail: 'support@laolottery.la',
  supportPhone: '+856 21 000 000',
  primaryDomain: 'admin.laolottery.la',
};

export const DEFAULT_REGIONAL: RegionalSettings = {
  locale: 'en-GB',
  currency: 'LAK',
  currencySymbol: '₭',
  currencyPosition: 'suffix',
  dateFormat: 'dd MMM yyyy',
  timeFormat: '24h',
  timezone: 'Asia/Vientiane',
  numberGrouping: true,
  firstDayOfWeek: 1,
};
